// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utjkkxrinjrvzfwlmnaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0amtreHJpbmpydnpmd2xtbmF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MDI2MzMsImV4cCI6MjA3MDk3ODYzM30.OsRMmqlXmWlyIsPWMYUzBG3KHFu4r4r3whufeM5ghNQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});