// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yatpjnhfwnsdgcbsvinu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhdHBqbmhmd25zZGdjYnN2aW51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NDY3ODEsImV4cCI6MjA3MDUyMjc4MX0.q_B6GHqwtDxXG4bC1TvkK7w3U0KI6GjUHUsH6z_JGxE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});